include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - build/**
    - android/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - require_trailing_commas
    - use_key_in_widget_constructors
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - always_declare_return_types
