import 'package:csv/csv.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../data/database/app_database.dart';
import 'dart:io';
import 'package:path_provider/path_provider.dart';

class ExportSessionsUseCase {
  Future<String> exportToCsv(List<Session> sessions) async {
    List<List<dynamic>> rows = [
      ['ID', 'Start', 'End', 'Start%', 'End%', 'AvgW', 'PeakW', 'MaxTemp', 'ChargerType'],
    ];
    for (var s in sessions) {
      rows.add([
        s.id,
        s.startTs,
        s.endTs,
        s.startPct,
        s.endPct,
        s.avgW,
        s.peakW,
        s.maxTemp,
        s.chargerType,
      ]);
    }
    String csv = const ListToCsvConverter().convert(rows);
    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/sessions_export.csv');
    await file.writeAsString(csv);
    return file.path;
  }

  Future<String> exportToPdf(List<Session> sessions) async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.MultiPage(
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Text(
                'Charge Tracker Battery Telemetry & Health Report',
                style: const pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
              ),
            ),
            pw.Paragraph(
              text: 'Generated by Charge Tracker 100% Offline Battery Monitor. Total sessions: ${sessions.length}',
            ),
            pw.SizedBox(height: 10),
            if (sessions.isEmpty)
              pw.Paragraph(text: 'No sessions recorded yet.')
            else
              pw.TableHelper.fromTextArray(
                headers: ['ID', 'Start %', 'End %', 'Avg Power', 'Peak Power', 'Max Temp', 'Charger'],
                data: sessions.map((s) {
                  return [
                    '#${s.id}',
                    '${s.startPct}%',
                    '${s.endPct ?? s.startPct}%',
                    s.avgW != null ? '${s.avgW!.toStringAsFixed(1)}W' : '--',
                    s.peakW != null ? '${s.peakW!.toStringAsFixed(1)}W' : '--',
                    s.maxTemp != null ? '${s.maxTemp!.toStringAsFixed(1)}°C' : '--',
                    s.chargerType,
                  ];
                }).toList(),
              ),
          ];
        },
      ),
    );
    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/sessions_export.pdf');
    await file.writeAsBytes(await pdf.save());
    return file.path;
  }
}
